## Today's Topic
1. Introduction to Pandas: 
- It is a package in Python that provides data structures and data analytics tools for working with structured data.

In [11]:
#  %pip install pandas ipykernel

In [12]:
import pandas as pd

In [13]:
csv_file = pd.read_csv("Day5_Finance_Transactions_Pandas.csv")

In [14]:
xl_file = pd.ExcelFile('Day5_Finance_Transactions_Pandas.xlsx')

In [15]:
xl_file.sheet_names

['Transactions', 'Data_Dictionary', 'Student_Tasks', 'Trainer_Checks']

In [16]:
trx_df = xl_file.parse('Transactions') ## ['Transactions] is the sheet name in excel file, or .parse('Transactions') can also be used to read the sheet

/tmp/ipykernel_146683/2470972687.py:1: Pandas4Warning: ExcelFile.parse is deprecated. Use pd.read_excel instead.
  trx_df = xl_file.parse('Transactions') ## ['Transactions] is the sheet name in excel file, or .parse('Transactions') can also be used to read the sheet

In [17]:
trx_df.head()

,transaction_id,transaction_date,department,expense_category,vendor,region,budget_amount,actual_amount,approval_status,payment_mode
0,FIN2026001,2026-09-08,Finance,Bank Charges,Nimbus Cloud,North,6750.75,5687.65,Approved,Cheque
1,FIN2026002,2026-09-17,Finance,Audit,Metro Office Mart,South,7085.81,5690.24,Paid,Corporate Card
2,FIN2026003,2026-09-01,IT,Hardware,Nimbus Cloud,West,46248.60,56266.11,Rejected,UPI
3,FIN2026004,2026-09-04,Operations,Logistics,Cedar Consulting,North,20071.96,23774.15,Rejected,UPI
4,FIN2026005,2026-09-15,HR,Recruitment,Cedar Consulting,North,23516.46,16000.96,Rejected,UPI

In [18]:
txn_df = pd.DataFrame(trx_df)

In [19]:
txn_df.head()

,transaction_id,transaction_date,department,expense_category,vendor,region,budget_amount,actual_amount,approval_status,payment_mode
0,FIN2026001,2026-09-08,Finance,Bank Charges,Nimbus Cloud,North,6750.75,5687.65,Approved,Cheque
1,FIN2026002,2026-09-17,Finance,Audit,Metro Office Mart,South,7085.81,5690.24,Paid,Corporate Card
2,FIN2026003,2026-09-01,IT,Hardware,Nimbus Cloud,West,46248.60,56266.11,Rejected,UPI
3,FIN2026004,2026-09-04,Operations,Logistics,Cedar Consulting,North,20071.96,23774.15,Rejected,UPI
4,FIN2026005,2026-09-15,HR,Recruitment,Cedar Consulting,North,23516.46,16000.96,Rejected,UPI

`.info()` method is used to get the concise summary of the dataframe. It provides info about your number of rows then data columns, their data types, and memory usage. It also provides information about the number of non-null values in each column.

In [20]:
txn_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    61 non-null     str
 1   transaction_date  61 non-null     str
 2   department        61 non-null     str
 3   expense_category  61 non-null     str
 4   vendor            61 non-null     str
 5   region            61 non-null     str
 6   budget_amount     61 non-null     float64
 7   actual_amount     58 non-null     float64
 8   approval_status   61 non-null     str
 9   payment_mode      61 non-null     str
dtypes: float64(2), str(8)
memory usage: 4.9 KB

### Shape of the dataframe
`.shape` attribute is used to get the shape of the dataframe. It returns a tuple representing the dimensionality of the dataframe, where the first element is the number of rows and the second element is the number of columns.

In [21]:
txn_df.shape

(61, 10)

### column names : 
`.columns` attribute is used to get the column names of the dataframe.

In [22]:
txn_df.columns

Index(['transaction_id', 'transaction_date', 'department', 'expense_category',
       'vendor', 'region', 'budget_amount', 'actual_amount', 'approval_status',
       'payment_mode'],
      dtype='str')

### Statistical summary of Dataframe/ Data: 
`.describe()` method is used to get the statistical summary of the dataframe. It provides information about count, mean, std, min, 25%, 50%, 75%, and max values of the numerical columns in the dataframe.

In [23]:
txn_df.describe()

       budget_amount  actual_amount
count      61.000000      58.000000
mean    35772.577705   33008.688448
std     19776.634570   22669.803585
min      6750.750000   -2016.230000
25%     20239.060000   14614.280000
50%     32975.700000   25810.875000
75%     51016.120000   50732.037500
max     74812.800000   92457.580000

- import pandas as pd 
- from pandas import * 
- pd.ExcelFile() earlier it is read_excel() method. It is used to read the excel file and return a ExcelFile object. It is used to read the excel file in pandas.
- trx_df.sheet_names : it is giving us the list of sheet names in the excel file. 
- trx_df.parse(sheet_name) : it is used to read the excel file and return a dataframe. It is used to read the excel file in pandas. It takes sheet_name as an argument which is the name of the sheet to be read. It returns a dataframe.
- trx_df.head() : It is used to get the first n rows from dataframe. By default, it returns the first 5 rows. It is used to get a quick overview of the dataframe.
- trx_df.tail() : It is used to get the last n rows from dataframe. By default, it returns the last 5 rows. It is used to get a quick overview of the dataframe.
- trx_df.sample(n) : It is used to get a random sample of n rows from dataframe. It is used to get a quick overview of the dataframe.
- pd.Dataframe(trx_df) : It is used to create a dataframe from the given data. It takes data as an argument which can be a list, dict, or ndarray. It returns a dataframe.
- txn_df.info() : It is used to get the concise summary of the dataframe. 
- txn_df.shape : It is used to get the shape of the dataframe.
- txn_df.columns : It is used to get the column names of the dataframe.
- txn_df.describe() : It is used to get the statistical summary of the dataframe.

In [24]:
txn_df.columns

Index(['transaction_id', 'transaction_date', 'department', 'expense_category',
       'vendor', 'region', 'budget_amount', 'actual_amount', 'approval_status',
       'payment_mode'],
      dtype='str')

## The Manager asks : 
Find out the Pending Transactions in the dataset.

In [25]:
txn_df[['transaction_id','department','budget_amount','actual_amount']].head()

  transaction_id  department  budget_amount  actual_amount
0     FIN2026001     Finance        6750.75        5687.65
1     FIN2026002     Finance        7085.81        5690.24
2     FIN2026003          IT       46248.60       56266.11
3     FIN2026004  Operations       20071.96       23774.15
4     FIN2026005          HR       23516.46       16000.96

In [26]:
pending_txn = txn_df[txn_df['approval_status'] == 'Pending']

In [27]:
pending_txn.head()

,transaction_id,transaction_date,department,expense_category,vendor,region,budget_amount,actual_amount,approval_status,payment_mode
5,FIN2026006,2026-09-22,HR,Training,BluePeak Logistics,North,18460.20,12897.93,Pending,Bank Transfer
6,FIN2026007,2026-09-12,IT,Hardware,BluePeak Logistics,East,24458.15,26781.16,Pending,UPI
11,FIN2026012,2026-09-16,Operations,Logistics,Northstar Services,North,74812.80,55872.61,Pending,Corporate Card
14,FIN2026015,2026-09-04,HR,Payroll,Nimbus Cloud,South,58337.35,58651.04,Pending,UPI
16,FIN2026017,2026-09-27,Finance,Compliance,Apex Technologies,North,70036.90,88604.05,Pending,Bank Transfer

In [28]:
pending_txn.shape

(19, 10)

#### Show 3 columns : transaction_id, department, budget_amount from pending_txn dataframe.

In [29]:
pending_txn[['transaction_id','department','budget_amount']]

   transaction_id  department  budget_amount
5      FIN2026006          HR       18460.20
6      FIN2026007          IT       24458.15
11     FIN2026012  Operations       74812.80
14     FIN2026015          HR       58337.35
16     FIN2026017     Finance       70036.90
17     FIN2026018     Finance       56233.53
24     FIN2026025  Operations       18314.62
27     FIN2026028          IT       23564.21
29     FIN2026030          HR       38375.20
31     FIN2026032          IT       51016.12
35     FIN2026036   Marketing       13080.01
39     FIN2026040          IT       13921.19
40     FIN2026041   Marketing       59608.14
49     FIN2026050          HR       44837.37
52     FIN2026053  Operations       15314.78
53     FIN2026054          IT       32975.70
55     FIN2026056          IT       47885.66
56     FIN2026057          IT       23143.41
57     FIN2026058          IT       10423.83

### Manager Asking : 
Find out how many approvals are pending in finance department. And find out the vendors also with actual amount. 
At last, show the highest budget transactions first.

In [30]:
condition = (txn_df['approval_status'] == 'Pending') & (txn_df['department'] == 'Finance')

finance_pending = txn_df.loc[condition,['transaction_id','vendor','budget_amount','actual_amount']]

In [31]:
finance_pending.sort_values('budget_amount', ascending=True).head()

   transaction_id             vendor  budget_amount  actual_amount
17     FIN2026018  Apex Technologies       56233.53       68673.30
16     FIN2026017  Apex Technologies       70036.90       88604.05

In [32]:
finance_pending

   transaction_id             vendor  budget_amount  actual_amount
16     FIN2026017  Apex Technologies       70036.90       88604.05
17     FIN2026018  Apex Technologies       56233.53       68673.30

#### Operators 
How many types of Operators are there in python ? 
1. Arithmetic Operators : +, -, *, /, %, **, //
2. Comparison Operators : ==, !=, >, <, >=, <=
3. Assignment Operators : =, +=, -=, *=, /=, %=, **=, //=
4. Logical Operators : and, or, not
5. Bitwise Operators : &, |, ^, ~, <<, >>
6. Membership Operators : in, not in
7. Identity Operators : is, is not

## Missing values, Negative values and duplicates in the dataset.

In [33]:
txn_df.shape
finance = txn_df.copy()

## null value check in the dataset:

In [34]:
finance.isna().sum()

transaction_id      0
transaction_date    0
department          0
expense_category    0
vendor              0
region              0
budget_amount       0
actual_amount       3
approval_status     0
payment_mode        0
dtype: int64

In [35]:
condition1 = (finance['actual_amount'].isna())
missing_actual = finance[condition1]
print(missing_actual.shape)
display(missing_actual)

(3, 10)

,transaction_id,transaction_date,department,expense_category,vendor,region,budget_amount,actual_amount,approval_status,payment_mode
7,FIN2026008,2026-09-24,Finance,Bank Charges,Apex Technologies,West,47639.17,NaN,Paid,UPI
22,FIN2026023,2026-09-04,IT,Cybersecurity,BluePeak Logistics,West,61524.79,NaN,Paid,Cheque
40,FIN2026041,2026-09-14,Marketing,Events,Apex Technologies,South,59608.14,NaN,Pending,Cheque

Negative values check in the dataset:

In [36]:
negative_actual = finance[finance['actual_amount'] < 0]
negative_budget = finance[finance['budget_amount'] < 0]

print(negative_actual.shape)
display(negative_actual)

print("Negative budget amount records: ", negative_budget.shape)
display(negative_budget)

(2, 10)

,transaction_id,transaction_date,department,expense_category,vendor,region,budget_amount,actual_amount,approval_status,payment_mode
13,FIN2026014,2026-09-10,HR,Employee Welfare,Apex Technologies,West,57561.45,-1520.53,Approved,UPI
36,FIN2026037,2026-09-09,Operations,Logistics,Northstar Services,West,53124.80,-2016.23,Rejected,Bank Transfer

Negative budget amount records:  (0, 10)

Empty DataFrame
Columns: [transaction_id, transaction_date, department, expense_category, vendor, region, budget_amount, actual_amount, approval_status, payment_mode]
Index: []

Duplicate values check in the dataset:

In [37]:
finance.duplicated().sum()

np.int64(1)

In [41]:
finance_clean = finance.drop_duplicates().copy()

In [ ]:
finance_clean.to_csv('finance_clean.csv', index=False)

### Methods we used above: 
- `.isna()` marks missing values as True and non-missing values as False.
- `.isna().sum()` counts the number of missing values in each column.
- `.isnull()` marks missing values as True and non-missing values as False.
- `< 0` checks for negative values in the dataframe.
- `.duplicated()` marks duplicate rows as True and non-duplicate rows as False.
- `.drop_duplicates()` removes duplicate rows from the dataframe.
- `.copy()` creates a separate copy of the dataframe to avoid modifying the original dataframe.

## DataFrame: 
A dataframe is a  labelled two-dimensional table.

In [38]:
data = { 
        'Name': ['John', 'Anna', 'Peter', 'Linda'],
        'Location' : ['New York', 'Paris', 'Berlin', 'London'],
        'Age' : [24, 13, 53, 33]
        }

data

{'Name': ['John', 'Anna', 'Peter', 'Linda'],
 'Location': ['New York', 'Paris', 'Berlin', 'London'],
 'Age': [24, 13, 53, 33]}

In [39]:
df = pd.DataFrame(data)

In [40]:
df

    Name  Location  Age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33